// Generated by repose.py: the Start Plank mocap (frame 38 = on your marks,
// frame 52 = set) retargeted onto real starting blocks. Feet are IK'd onto the
// pedals defined in Stadium.startingBlock, hands onto the track just behind
// the line, hips lifted to set/marks heights. Regenerate by re-running the
// script; do not hand-edit.
import SceneKit

enum BlockPose {
    static let marks: [(String, SCNQuaternion)] = [
        ("Hips", SCNQuaternion(0.556849, 0.085399, 0.042850, 0.825100)),
        ("Spine", SCNQuaternion(0.035458, 0.004867, 0.004768, 0.999348)),
        ("Spine1", SCNQuaternion(0.136943, 0.011850, -0.001148, 0.990507)),
        ("Spine2", SCNQuaternion(0.189177, 0.013425, -0.010106, 0.981799)),
        ("Neck", SCNQuaternion(-0.109424, -0.027064, 0.082121, 0.990227)),
        ("Head", SCNQuaternion(0.011692, -0.043791, -0.034857, 0.998364)),
        ("LeftShoulder", SCNQuaternion(0.483021, 0.403325, -0.374805, 0.680838)),
        ("LeftArm", SCNQuaternion(0.161631, -0.400495, 0.387332, 0.814526)),
        ("LeftForeArm", SCNQuaternion(0.026143, -0.052755, 0.392200, 0.917994)),
        ("LeftHand", SCNQuaternion(-0.464057, -0.019475, -0.015829, 0.885450)),
        ("RightShoulder", SCNQuaternion(0.515697, -0.472482, 0.445216, 0.559106)),
        ("RightArm", SCNQuaternion(0.042755, 0.370064, -0.220873, 0.901354)),
        ("RightForeArm", SCNQuaternion(0.078280, 0.022458, -0.559031, 0.825138)),
        ("RightHand", SCNQuaternion(-0.580168, 0.064272, 0.249117, 0.772797)),
        ("LeftUpLeg", SCNQuaternion(0.079064, 0.958033, 0.268530, 0.061754)),
        ("LeftLeg", SCNQuaternion(0.890495, -0.009149, 0.056843, -0.451335)),
        ("LeftFoot", SCNQuaternion(0.899523, 0.047135, -0.123463, 0.416406)),
        ("LeftToeBase", SCNQuaternion(0.416677, 0.006669, -0.099890, 0.903525)),
        ("RightUpLeg", SCNQuaternion(-0.058671, 0.740143, 0.669596, 0.019661)),
        ("RightLeg", SCNQuaternion(-0.860815, 0.088897, -0.025373, 0.500450)),
        ("RightFoot", SCNQuaternion(0.992180, -0.032259, -0.048190, -0.110528)),
        ("RightToeBase", SCNQuaternion(0.444938, 0.146442, 0.022242, 0.883227)),
    ]
    /// Hips local translation for this pose (model units).
    static let marksHips = SCNVector3(-10.3352, 103.3523, -72.3466)
    static let set: [(String, SCNQuaternion)] = [
        ("Hips", SCNQuaternion(0.695802, 0.065052, 0.011346, 0.715191)),
        ("Spine", SCNQuaternion(0.062520, -0.007987, 0.008776, 0.997973)),
        ("Spine1", SCNQuaternion(0.158299, -0.016931, -0.002786, 0.987242)),
        ("Spine2", SCNQuaternion(0.210740, -0.015326, -0.008939, 0.977381)),
        ("Neck", SCNQuaternion(-0.138012, -0.016199, 0.024158, 0.990003)),
        ("Head", SCNQuaternion(-0.018176, -0.011901, -0.013635, 0.999671)),
        ("LeftShoulder", SCNQuaternion(0.488521, 0.411717, -0.221221, 0.736816)),
        ("LeftArm", SCNQuaternion(-0.112582, -0.446144, 0.017319, 0.887683)),
        ("LeftForeArm", SCNQuaternion(0.060996, -0.009146, 0.487330, 0.871037)),
        ("LeftHand", SCNQuaternion(-0.575613, -0.187778, -0.164562, 0.778671)),
        ("RightShoulder", SCNQuaternion(0.446317, -0.511792, 0.330759, 0.655338)),
        ("RightArm", SCNQuaternion(0.040416, 0.495097, -0.243641, 0.832997)),
        ("RightForeArm", SCNQuaternion(0.044276, 0.020069, -0.455005, 0.889161)),
        ("RightHand", SCNQuaternion(-0.576629, -0.011179, 0.301960, 0.759075)),
        ("LeftUpLeg", SCNQuaternion(0.062607, 0.920162, 0.385644, 0.025700)),
        ("LeftLeg", SCNQuaternion(-0.696931, -0.010440, -0.059643, 0.714577)),
        ("LeftFoot", SCNQuaternion(0.884618, 0.057065, -0.146648, 0.438964)),
        ("LeftToeBase", SCNQuaternion(0.423585, -0.001546, -0.096654, 0.900684)),
        ("RightUpLeg", SCNQuaternion(0.079122, 0.753424, 0.652596, 0.014494)),
        ("RightLeg", SCNQuaternion(-0.571368, 0.086047, -0.007672, 0.816134)),
        ("RightFoot", SCNQuaternion(0.979932, 0.007222, -0.129010, 0.151781)),
        ("RightToeBase", SCNQuaternion(0.491524, 0.135519, 0.011088, 0.860183)),
    ]
    /// Hips local translation for this pose (model units).
    static let setHips = SCNVector3(-10.3352, 148.8274, -51.6762)
}
