// Generated by repose.py: the Start Plank mocap (frame 38 = on your marks,
// frame 52 = set) retargeted onto real starting blocks. Feet are IK'd onto the
// pedals defined in Stadium.startingBlock, hands onto the track just behind
// the line, hips lifted to set/marks heights. Regenerate by re-running the
// script; do not hand-edit.
import SceneKit

enum BlockPose {
    static let marks: [(String, SCNQuaternion)] = [
        ("Hips", SCNQuaternion(0.556849, 0.085399, 0.042850, 0.825100)),
        ("Spine", SCNQuaternion(0.035458, 0.004867, 0.004768, 0.999348)),
        ("Spine1", SCNQuaternion(0.136943, 0.011850, -0.001148, 0.990507)),
        ("Spine2", SCNQuaternion(0.189177, 0.013425, -0.010106, 0.981799)),
        ("Neck", SCNQuaternion(-0.109424, -0.027064, 0.082121, 0.990227)),
        ("Head", SCNQuaternion(0.011692, -0.043791, -0.034857, 0.998364)),
        ("LeftShoulder", SCNQuaternion(0.520125, 0.410194, -0.384865, 0.642721)),
        ("LeftArm", SCNQuaternion(0.182096, -0.372113, 0.388223, 0.823198)),
        ("LeftForeArm", SCNQuaternion(0.023086, -0.028673, 0.415046, 0.909055)),
        ("LeftHand", SCNQuaternion(-0.493603, -0.006863, 0.009820, 0.869605)),
        ("RightShoulder", SCNQuaternion(0.552051, -0.469790, 0.443117, 0.527432)),
        ("RightArm", SCNQuaternion(0.066732, 0.344645, -0.226548, 0.908539)),
        ("RightForeArm", SCNQuaternion(0.070874, -0.005696, -0.575769, 0.814515)),
        ("RightHand", SCNQuaternion(-0.617934, 0.044997, 0.238740, 0.747754)),
        ("LeftUpLeg", SCNQuaternion(0.095180, 0.916432, 0.384950, 0.053910)),
        ("LeftLeg", SCNQuaternion(-0.855950, 0.005062, -0.057351, 0.513843)),
        ("LeftFoot", SCNQuaternion(0.957733, 0.098294, -0.230293, 0.141600)),
        ("LeftToeBase", SCNQuaternion(0.365199, -0.012002, -0.046651, 0.929682)),
        ("RightUpLeg", SCNQuaternion(-0.056293, 0.707554, 0.704316, 0.011726)),
        ("RightLeg", SCNQuaternion(-0.800056, 0.085537, -0.035068, 0.592759)),
        ("RightFoot", SCNQuaternion(0.949278, 0.024210, -0.120791, -0.289301)),
        ("RightToeBase", SCNQuaternion(0.647349, 0.130145, 0.021098, 0.750704)),
    ]
    /// Hips local translation for this pose (model units).
    static let marksHips = SCNVector3(-10.3352, 103.3523, -55.8103)
    static let set: [(String, SCNQuaternion)] = [
        ("Hips", SCNQuaternion(0.695802, 0.065052, 0.011346, 0.715191)),
        ("Spine", SCNQuaternion(0.062520, -0.007987, 0.008776, 0.997973)),
        ("Spine1", SCNQuaternion(0.158299, -0.016931, -0.002786, 0.987242)),
        ("Spine2", SCNQuaternion(0.210740, -0.015326, -0.008939, 0.977381)),
        ("Neck", SCNQuaternion(-0.138012, -0.016199, 0.024158, 0.990003)),
        ("Head", SCNQuaternion(-0.018176, -0.011901, -0.013635, 0.999671)),
        ("LeftShoulder", SCNQuaternion(0.488521, 0.411717, -0.221221, 0.736816)),
        ("LeftArm", SCNQuaternion(-0.112582, -0.446144, 0.017319, 0.887683)),
        ("LeftForeArm", SCNQuaternion(0.060996, -0.009146, 0.487330, 0.871037)),
        ("LeftHand", SCNQuaternion(-0.575613, -0.187778, -0.164562, 0.778671)),
        ("RightShoulder", SCNQuaternion(0.446317, -0.511792, 0.330759, 0.655338)),
        ("RightArm", SCNQuaternion(0.040416, 0.495097, -0.243641, 0.832997)),
        ("RightForeArm", SCNQuaternion(0.044276, 0.020069, -0.455005, 0.889161)),
        ("RightHand", SCNQuaternion(-0.576629, -0.011179, 0.301960, 0.759075)),
        ("LeftUpLeg", SCNQuaternion(0.054351, 0.901571, 0.428110, 0.030615)),
        ("LeftLeg", SCNQuaternion(-0.602102, -0.017816, -0.057869, 0.796120)),
        ("LeftFoot", SCNQuaternion(0.939662, 0.054640, -0.194310, 0.276211)),
        ("LeftToeBase", SCNQuaternion(0.406968, -0.022015, -0.049381, 0.911841)),
        ("RightUpLeg", SCNQuaternion(0.084251, 0.744666, 0.661754, 0.021344)),
        ("RightLeg", SCNQuaternion(-0.483764, 0.084790, -0.016543, 0.870925)),
        ("RightFoot", SCNQuaternion(0.990382, 0.006742, -0.138120, -0.004609)),
        ("RightToeBase", SCNQuaternion(0.652038, 0.117883, 0.014867, 0.748819)),
    ]
    /// Hips local translation for this pose (model units).
    static let setHips = SCNVector3(-10.3352, 148.8274, -51.6762)
}
